-- Entire intake as real database roles, with synthetic Storage metadata only. No API calls.
BEGIN;
SET LOCAL statement_timeout='25s';
DO $test$
DECLARE c uuid:=gen_random_uuid(); other_c uuid:=gen_random_uuid(); u uuid:=gen_random_uuid(); u2 uuid:=gen_random_uuid();
 admin_id uuid:=gen_random_uuid(); foreign_id uuid:=gen_random_uuid(); a uuid; a2 uuid; d uuid; d2 uuid; category uuid; foreign_category uuid;
 car uuid:=gen_random_uuid(); licence uuid:=gen_random_uuid(); insurance uuid:=gen_random_uuid(); reg uuid:=gen_random_uuid();
 licence2 uuid:=gen_random_uuid(); insurance2 uuid:=gen_random_uuid(); bad_insurance uuid:=gen_random_uuid();
 today date:=(now() AT TIME ZONE 'Europe/Sofia')::date; terms text; privacy text; m jsonb; receipt jsonb; retry jsonb;
 bundle jsonb; revision integer; denied boolean; path text; kind text; doc_id uuid; expires date;
 answers jsonb:='{"background":"foreground","cash":"reconcile","responsibility":"carrier"}';
BEGIN
 SELECT terms_version,privacy_version INTO STRICT terms,privacy FROM private.legal_versions WHERE is_current;
 INSERT INTO public.companies(id,name,slug,permit_expires_on) VALUES(c,'Unified fixture','unified-'||c,today+90),(other_c,'Other fixture','unified-'||other_c,today+90);
 SELECT id INTO STRICT category FROM public.vehicle_types WHERE company_id=c;
 SELECT id INTO STRICT foreign_category FROM public.vehicle_types WHERE company_id=other_c;
 INSERT INTO auth.users(id,email) SELECT x,'unified-'||x||'@example.invalid' FROM unnest(ARRAY[u,u2,admin_id,foreign_id])s(x);
 UPDATE public.profiles SET role='COMPANY_ADMIN',company_id=c WHERE id=admin_id;
 UPDATE public.profiles SET role='COMPANY_ADMIN',company_id=other_c WHERE id=foreign_id;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true); SET LOCAL ROLE authenticated;
 a:=public.begin_driver_onboarding(c,'Unified Driver','+359000000000','1–3',true,'');
 IF EXISTS(SELECT 1 FROM public.drivers WHERE user_id=u) OR (SELECT role FROM public.profiles WHERE id=u)<>'CUSTOMER' THEN RAISE EXCEPTION 'FAIL invitation grants driver privileges'; END IF;
 bundle:=public.driver_onboarding(a); m:=bundle->'preparation';
 denied:=false;BEGIN PERFORM public.submit_driver_onboarding(a,0);EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL incomplete package submitted'; END IF;
 denied:=false;BEGIN PERFORM public.verify_driver_application(a,0,NULL,category,true);EXCEPTION WHEN insufficient_privilege THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL self verification'; END IF;
 denied:=false;BEGIN PERFORM public.accept_application_preparation(a,m#>>'{document,termsVersion}',m#>>'{document,trainingVersion}',m->>'content_hash','{}',terms,privacy);EXCEPTION WHEN invalid_parameter_value THEN denied:=true;END;
 IF NOT denied OR EXISTS(SELECT 1 FROM public.driver_application_acceptances WHERE application_id=a) THEN RAISE EXCEPTION 'FAIL wrong quiz'; END IF;
 receipt:=public.accept_application_preparation(a,m#>>'{document,termsVersion}',m#>>'{document,trainingVersion}',m->>'content_hash',answers,terms,privacy);
 retry:=public.accept_application_preparation(a,m#>>'{document,termsVersion}',m#>>'{document,trainingVersion}',m->>'content_hash',answers,terms,privacy);
 IF receipt IS DISTINCT FROM retry THEN RAISE EXCEPTION 'FAIL duplicate preparation'; END IF;
 PERFORM public.save_application_vehicle(a,true,jsonb_build_object('make','Test','model','Own','registration_number','U-'||left(a::text,8),'insurance_expiry_date',today+30,'inspection_expiry_date',today+60));
 FOREACH kind IN ARRAY ARRAY['license','insurance','vehicle_registration'] LOOP
  doc_id:=CASE kind WHEN 'license' THEN licence WHEN 'insurance' THEN insurance ELSE reg END;
  expires:=CASE kind WHEN 'vehicle_registration' THEN NULL ELSE today+30 END;
  path:=u||'/'||a||'/'||doc_id||'.pdf';
  INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES('driver-documents',path,u::text,'{"mimetype":"application/pdf","size":100}');
  PERFORM public.register_application_document(a,doc_id,kind::public.document_type,expires,path);
  PERFORM public.register_application_document(a,doc_id,kind::public.document_type,expires,path);
 END LOOP;
 IF (SELECT count(*) FROM public.driver_application_documents WHERE application_id=a)<>3 THEN RAISE EXCEPTION 'FAIL duplicate files'; END IF;
 denied:=false;BEGIN UPDATE public.driver_application_documents SET expires_at=today+100 WHERE id=licence;EXCEPTION WHEN insufficient_privilege THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL editable file evidence'; END IF;
 revision:=(public.driver_onboarding(a)#>>'{application,onboarding_revision}')::integer;
 denied:=false;BEGIN PERFORM public.submit_driver_onboarding(a,revision-1);EXCEPTION WHEN serialization_failure THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL stale package submit'; END IF;
 PERFORM public.submit_driver_onboarding(a,revision); PERFORM public.submit_driver_onboarding(a,revision);
 RESET ROLE;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',admin_id,'role','authenticated')::text,true); SET LOCAL ROLE authenticated;
 PERFORM public.review_driver_application(a,'rejected','Проверете четливостта на книжката.');
 RESET ROLE;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',u,'role','authenticated')::text,true); SET LOCAL ROLE authenticated;
 PERFORM public.reopen_driver_onboarding(a); PERFORM public.reopen_driver_onboarding(a);
 bundle:=public.driver_onboarding(a); revision:=(bundle#>>'{application,onboarding_revision}')::integer;
 IF bundle#>>'{application,submitted_at}' IS NOT NULL OR jsonb_array_length(bundle->'documents')<>3 OR bundle#>>'{preparation,receipt,id}' IS NULL THEN RAISE EXCEPTION 'FAIL correction discards preparation or keeps stale submission'; END IF;
 PERFORM public.submit_driver_onboarding(a,revision);
 IF jsonb_array_length(public.export_my_basic_data()->'driver_application_documents')<>3 OR jsonb_array_length(public.export_my_basic_data()->'driver_application_acceptances')<>1 THEN RAISE EXCEPTION 'FAIL candidate data export'; END IF;
 RESET ROLE;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',foreign_id,'role','authenticated')::text,true); SET LOCAL ROLE authenticated;
 IF EXISTS(SELECT 1 FROM public.driver_application_documents WHERE application_id=a) OR EXISTS(SELECT 1 FROM storage.objects WHERE bucket_id='driver-documents' AND name LIKE u||'/%') THEN RAISE EXCEPTION 'FAIL cross-company files'; END IF;
 denied:=false;BEGIN PERFORM private.verify_driver_application(a,revision,NULL,category,true,'');EXCEPTION WHEN insufficient_privilege THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL private core cross-company bypass'; END IF;
 denied:=false;BEGIN PERFORM public.driver_onboarding(a);EXCEPTION WHEN insufficient_privilege THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL cross-company material access'; END IF;
 RESET ROLE;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',admin_id,'role','authenticated')::text,true); SET LOCAL ROLE authenticated;
 denied:=false;BEGIN PERFORM public.accept_application_preparation(a,m#>>'{document,termsVersion}',m#>>'{document,trainingVersion}',m->>'content_hash',answers,terms,privacy);EXCEPTION WHEN insufficient_privilege THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL admin accepts personally for candidate'; END IF;
 denied:=false;BEGIN PERFORM public.review_driver_application(a,'approved','');EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL old endpoint skips unified review'; END IF;
 denied:=false;BEGIN PERFORM public.verify_driver_application(a,revision-1,NULL,category,true);EXCEPTION WHEN serialization_failure THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL stale review'; END IF;
 denied:=false;BEGIN PERFORM public.verify_driver_application(a,revision,NULL,foreign_category,true);EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL foreign vehicle category'; END IF;
 denied:=false;BEGIN PERFORM public.verify_driver_application(a,revision,NULL,category,false);EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL no review attestation'; END IF;
 RESET ROLE;
 UPDATE public.companies SET permit_expires_on=today-1 WHERE id=c;
 SET LOCAL ROLE authenticated;
 denied:=false;BEGIN PERFORM public.verify_driver_application(a,revision,NULL,category,true);EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL expired carrier'; END IF;
 RESET ROLE;
 IF EXISTS(SELECT 1 FROM public.drivers WHERE user_id=u) OR EXISTS(SELECT 1 FROM public.vehicles WHERE company_id=c) OR (SELECT role FROM public.profiles WHERE id=u)<>'CUSTOMER' THEN RAISE EXCEPTION 'FAIL partial failed activation'; END IF;
 UPDATE public.companies SET permit_expires_on=today+90 WHERE id=c;
 SET LOCAL ROLE authenticated;
 d:=public.verify_driver_application(a,revision,NULL,category,true);
 IF public.verify_driver_application(a,revision,NULL,category,true)<>d THEN RAISE EXCEPTION 'FAIL lost approval response duplicate'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.drivers WHERE id=d AND is_verified AND NOT is_online AND status='offline' AND vehicle_id IS NOT NULL AND document_verification_required)
  OR (SELECT count(*) FROM public.driver_documents WHERE driver_id=d AND status='approved' AND reviewed_by=admin_id)<>3
  OR NOT private.driver_documents_ready(d) THEN RAISE EXCEPTION 'FAIL atomic approval state'; END IF;
 IF NOT EXISTS(SELECT 1 FROM public.driver_preparation_acceptances WHERE driver_id=d AND accepted_at=(receipt->>'accepted_at')::timestamptz AND content_hash=receipt->>'content_hash') THEN RAISE EXCEPTION 'FAIL personal receipt transfer'; END IF;
 IF (SELECT count(*) FROM public.audit_log WHERE entity_id=a AND action='application_verified')<>1 THEN RAISE EXCEPTION 'FAIL duplicate activation audit'; END IF;
 RESET ROLE;
 -- A candidate without a car uploads only the licence. Company insurance and car are resolved in this same review.
 INSERT INTO public.vehicles(id,company_id,make,model,registration_number,vehicle_type_id,insurance_expiry_date,inspection_expiry_date)
 VALUES(car,c,'Test','Company','C-'||left(car::text,8),category,today+30,today+60);
 PERFORM set_config('request.jwt.claims',json_build_object('sub',u2,'role','authenticated')::text,true); SET LOCAL ROLE authenticated;
 a2:=public.begin_driver_onboarding(c,'No Car Driver','+359000000001','1–3',false,''); m:=public.driver_onboarding(a2)->'preparation';
 PERFORM public.accept_application_preparation(a2,m#>>'{document,termsVersion}',m#>>'{document,trainingVersion}',m->>'content_hash',answers,terms,privacy);
 path:=u2||'/'||a2||'/'||licence2||'.pdf';
 INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES('driver-documents',path,u2::text,'{"mimetype":"application/pdf","size":100}');
 PERFORM public.register_application_document(a2,licence2,'license',today+30,path);
 revision:=(public.driver_onboarding(a2)#>>'{application,onboarding_revision}')::integer;
 PERFORM public.submit_driver_onboarding(a2,revision);
 RESET ROLE;
 PERFORM set_config('request.jwt.claims',json_build_object('sub',admin_id,'role','authenticated')::text,true); SET LOCAL ROLE authenticated;
 denied:=false;BEGIN PERFORM public.verify_driver_application(a2,revision,car,NULL,true);EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL missing company insurance'; END IF;
 path:=u2||'/'||a2||'/'||bad_insurance||'.pdf';
 INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES('driver-documents',path,admin_id::text,'{"mimetype":"application/pdf","size":100}');
 PERFORM public.register_application_document(a2,bad_insurance,'insurance',today+31,path);
 revision:=(public.driver_onboarding(a2)#>>'{application,onboarding_revision}')::integer;
 denied:=false;BEGIN PERFORM public.verify_driver_application(a2,revision,car,NULL,true);EXCEPTION WHEN OTHERS THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL mismatched insurance expiry'; END IF;
 path:=u2||'/'||a2||'/'||insurance2||'.pdf';
 INSERT INTO storage.objects(bucket_id,name,owner_id,metadata) VALUES('driver-documents',path,admin_id::text,'{"mimetype":"application/pdf","size":100}');
 PERFORM public.register_application_document(a2,insurance2,'insurance',today+30,path);
 bundle:=public.driver_onboarding(a2); revision:=(bundle#>>'{application,onboarding_revision}')::integer;
 IF bundle#>>'{application,submitted_at}' IS NULL THEN RAISE EXCEPTION 'FAIL admin upload loses candidate submission'; END IF;
 d2:=public.verify_driver_application(a2,revision,car,NULL,true);
 IF NOT EXISTS(SELECT 1 FROM public.drivers WHERE id=d2 AND vehicle_id=car AND is_verified) THEN RAISE EXCEPTION 'FAIL no-car activation'; END IF;
 RESET ROLE; SET LOCAL ROLE anon;
 denied:=false;BEGIN PERFORM public.driver_onboarding(a);EXCEPTION WHEN insufficient_privilege THEN denied:=true;END;
 IF NOT denied THEN RAISE EXCEPTION 'FAIL anonymous intake access'; END IF;
 RESET ROLE;
 PERFORM set_config('leski.unified_onboarding',jsonb_build_object('passed',true,'activation','atomic, audited, idempotent and offline','candidate','no DRIVER privileges before review','privacy','private files and cross-company isolation','training','personal current-version receipt','vehicle','own or assigned company car','network','same-ID recovery and stale review detection')::text,true);
END $test$;
SELECT current_setting('leski.unified_onboarding')::jsonb AS result;
ROLLBACK;
