-- Exact restoration of privileges removed by the approved package.
-- Snapshot: 2026-10-07T15:46:06.913178+00:00
-- Does not revert application rows, schemas, or grants made later to other objects.
BEGIN;
SET LOCAL lock_timeout='3s';
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."request_declines" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."request_declines" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."news_articles" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."news_articles" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."profiles" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."profiles" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."vehicle_types" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."vehicle_types" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."vehicles" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."vehicles" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."ratings" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."ratings" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."driver_locations" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."driver_locations" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."notifications" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."notifications" TO "authenticated";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."trips" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."trips" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."payment_transactions" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."payment_transactions" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."saved_places" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."saved_places" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."coupons" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."coupons" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."drivers" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."drivers" TO "authenticated";
GRANT UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."taxi_requests" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."taxi_requests" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."audit_log" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."audit_log" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."ledger" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."ledger" TO "authenticated";
GRANT DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."push_subscriptions" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."push_subscriptions" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."driver_documents" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."driver_documents" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."app_config" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."app_config" TO "authenticated";
GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."companies" TO "anon";
GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."companies" TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA public GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA public GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLES TO "authenticated";
NOTIFY pgrst, 'reload schema';
COMMIT;
